# Use an official lightweight Java runtime as a parent image
FROM eclipse-temurin:17-jre-alpine

# Set the working directory inside the container
WORKDIR /app

# Correctly copy the fat jar and rename it to app.jar inside the container
COPY server/build/libs/server-all.jar app.jar

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the single jar file we copied
CMD ["java", "-jar", "app.jar"]